apiVersion: v2
name: websub-consolidator
description: A Helm chart for Websub Cconsolidator
type: application
version: 12.0.2
appVersion: 12.0.2
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - websub-consolidator
  - websub
maintainers:
  - email: info@mosip.io
    name: MOSIP
