apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-post"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      serviceAccountName: {{ template "pmp-ui.serviceAccountName" . }}
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: bitnami/kubectl:1.22.9
        command:
        - /bin/bash
        - -c
        - |
            #!/bin/bash
            # Function to label the namespace with Istio injection

            echo "updating gateways host and virtual services "
            function update_yaml_with_pmp_gateway_host() {
                # Get PMP_HOST value from ConfigMap
                PMP_HOST=$(kubectl get cm global -o jsonpath={.data.mosip-pmp-host})
                # Fetch the YAML from Kubernetes
                YAML_CONTENT=$(kubectl get -n "{{ .Release.Namespace }}" gateways pmp-gateway -o yaml)
                # Replace the placeholder with ADMIN_HOST value
                UPDATED_YAML_CONTENT=$(sed -i "/^\s*hosts:/ {n;s/^\s*-.*$/    - $PMP_HOST/}" <<<"$YAML_CONTENT")
                # Apply the updated YAML content
                echo "$UPDATED_YAML_CONTENT" | kubectl apply -f -
                echo "GATEWAY  updated successfully with PMP_HOST value."
            }
            update_yaml_with_pmp_gateway_host
            function label_namespace_with_istio_injection() {
              echo "Labeling namespace "{{ .Release.Namespace }}" with Istio injection"
              kubectl label ns "{{ .Release.Namespace }}" istio-injection=enabled --overwrite
            }

            # Label the namespace with Istio injection for the destination namespace
            label_namespace_with_istio_injection
            set -e
            set -o errexit
            set -o nounset
            set -o errtrace
            set -o pipefail
            update_yaml_with_prereg_gateway_host
