apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        sidecar.istio.io/inject: "false"      
    spec:
      serviceAccountName: {{ include "mock-smtp.serviceAccountName" . }}
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: bitnami/kubectl:1.26.8
        command:
        - /bin/bash
        - -c
        - |
            #!/bin/bash
            # Copy configmaps and secrets from other namespaces
            echo Istio label
            kubectl label ns {{ .Release.Namespace }} istio-injection=enabled --overwrite

            # Function to copy ConfigMaps or Secrets
            function copy_resource() {
              local RESOURCE_TYPE="$1"
              local RESOURCE_NAME="$2"
              local SOURCE_NAMESPACE="$3"
              local DESTINATION_NAMESPACE="$4"
              local NEW_NAME="${5:-$RESOURCE_NAME}"

              if [ "$RESOURCE_TYPE" = "configmap" ]; then
                RESOURCE="configmap"
              elif [ "$RESOURCE_TYPE" = "secret" ]; then
                RESOURCE="secret"
              else
                echo "Incorrect resource type: $RESOURCE_TYPE. Exiting..."
                exit 1
              fi

              if [ "$NEW_NAME" != "$RESOURCE_NAME" ]; then
                kubectl -n "$DESTINATION_NAMESPACE" delete --ignore-not-found=true "$RESOURCE" "$NEW_NAME"
                kubectl -n "$SOURCE_NAMESPACE" get "$RESOURCE" "$RESOURCE_NAME" -o yaml | \
                  sed "s/namespace: $SOURCE_NAMESPACE/namespace: $DESTINATION_NAMESPACE/g" | \
                  sed "s/name: $RESOURCE_NAME/name: $NEW_NAME/g" | kubectl -n "$DESTINATION_NAMESPACE" create -f -
              else
                kubectl -n "$DESTINATION_NAMESPACE" delete --ignore-not-found=true "$RESOURCE" "$RESOURCE_NAME"
                kubectl -n "$SOURCE_NAMESPACE" get "$RESOURCE" "$RESOURCE_NAME" -o yaml | \
                  sed "s/namespace: $SOURCE_NAMESPACE/namespace: $DESTINATION_NAMESPACE/g" | \
                  kubectl -n "$DESTINATION_NAMESPACE" create -f -
              fi
            }

            # Function to copy multiple ConfigMaps and Secrets
            function copy_resources() {
              # Copy ConfigMaps
              copy_resource "configmap" "global" "default" "{{ .Release.Namespace }}"
            }

            # Error handling settings
            set -e
            set -o errexit
            set -o nounset
            set -o errtrace
            set -o pipefail

            copy_resources
            echo "updating gateways host  "
            function update_yaml_with_smtp_gateway_host() {
                # Get SMTP_HOST value from ConfigMap
                SMTP_HOST=$(kubectl get cm global -o jsonpath={.data.mosip-smtp-host})
                # Fetch the YAML from Kubernetes
                YAML_CONTENT=$(kubectl get -n "{{ .Release.Namespace }}" gateways "{{.Release.Name}}-gateway" -o yaml)
                # Replace the placeholder with SMTP_HOST value
                UPDATED_YAML_CONTENT=$(sed "s/smtp\.sandbox\.xyz\.net/$SMTP_HOST/g" <<<"$YAML_CONTENT")
                # Apply the updated YAML content
                echo "$UPDATED_YAML_CONTENT" | kubectl apply -f -
                echo "GATEWAY  updated successfully with SMTP_HOST value."
            }

            set -e
            set -o errexit
            set -o nounset
            set -o errtrace
            set -o pipefail
            update_yaml_with_smtp_gateway_host