apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/sync-wave": "-5"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      serviceAccountName: {{ template "admin-service.serviceAccountName" . }}
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: bitnami/kubectl:1.22.9
        command:
        - /bin/bash
        - -c
        - |
            #!/bin/bash
            echo "updating virtualservice cors policy"
            function update_yaml_with_admin_host() {
                # Get ADMIN_HOST value from ConfigMap
                ADMIN_HOST=$(kubectl get cm global -o jsonpath={.data.mosip-admin-host})
                # Fetch the YAML from Kubernetes
                YAML_CONTENT=$(kubectl get -n "{{ .Release.Namespace }}" virtualservices "{{.Release.Name}}" -o yaml)
                # Replace the placeholder with PMP_HOST value
                UPDATED_YAML_CONTENT=$(echo "$YAML_CONTENT" | sed "s|https://.*|https://$ADMIN_HOST|g")
                # Apply the updated YAML content
                echo "$UPDATED_YAML_CONTENT" | kubectl apply -f -
                echo "YAML file updated successfully with ADMIN_HOST value."
            }
            update_yaml_with_admin_host
            set -e
            set -o errexit
            set -o nounset
            set -o errtrace
            set -o pipefail
